service: backend
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
functions:
  hello:
    handler: handler.hello
# you can add CloudFormation resource templates here
resources:
  Resources:
    clientBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:stage, 'dev'}-react-site
        WebsiteConfiguration:
          IndexDocument: index.html
    clientCloudFrontAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'Used for react site'
    clientBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: "clientBucket"
        PolicyDocument:
          Statement:
            -
              Action:
                - "s3:GetObject"
              Effect: "Allow"
              Principal:
                CanonicalUser: !GetAtt
                  - clientCloudFrontAccessIdentity
                  - S3CanonicalUserId
              Resource:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    -
                      Ref: "clientBucket"
                    - "/*"
    myDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          CustomErrorResponses:
            - ErrorCachingMinTTL: 5
              ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: '/index.html'
            - ErrorCachingMinTTL: 5
              ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: '/index.html'
          DefaultCacheBehavior:
            TargetOriginId: clientOrigin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
          DefaultRootObject: 'index.html'
          Enabled: 'true'
          Origins:
            - DomainName: !GetAtt
                - clientBucket
                - DomainName
              Id: clientOrigin
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - ''
                    -
                      - 'origin-access-identity/cloudfront/'
                      - Ref: clientCloudFrontAccessIdentity
